# Generated by Django 4.2.7 on 2023-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_token_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verify',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
